### ISSUE TITLE
aidea-server_1  | exec /usr/local/bin/aidea-server: exec format error 报错

### ISSUE THREAD

**Issue by reikiplanet** [mylxsw/aidea-docker#1]
aidea-server_1  | exec /usr/local/bin/aidea-server: exec format error
aidea-server_1  | exec /usr/local/bin/aidea-server: exec format error
aidea-server_1  | exec /usr/local/bin/aidea-server: exec format error
aidea-server_1  | exec /usr/local/bin/aidea-server: exec format error
aidea-server_1  | exec /usr/local/bin/aidea-server: exec format error
aidea-server_1  | exec /usr/local/bin/aidea-server: exec format error
aidea-server_1  | exec /usr/local/bin/aidea-server: exec format error
aidea-server_1  | exec /usr/local/bin/aidea-server: exec format error
aidea-server_1  | exec /usr/local/bin/aidea-server: exec format error
为什么docker-compose up  一直报错，无法正常使用

**Comment by reikiplanet** [comment]
解决办法：
服务端镜像用latest镜像，web端用1.0.9 解决二进制问题。
是否可以把配置文件写的更清楚一些呢，例如nginx的配置文件里，哪里要修改；server 配置文件里面哪里需要修改

**Comment by mylxsw** [comment]
感谢反馈，可能是打包时出了问题，我电脑是 ARM 芯片的，没在 x86 测试，我晚点改一下

**Comment by mylxsw** [comment]
已修复，删除掉原来的镜像重新启动即可。

```bash
docker rmi mylxsw/aidea-server:1.0.9
```
